# Generated by Django 5.0.3 on 2024-04-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Producto",
                "verbose_name_plural": "historical Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.RemoveField(
            model_name="categoryproduct",
            name="measure_unit",
        ),
        migrations.RemoveField(
            model_name="historicalcategoryproduct",
            name="measure_unit",
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="measure_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.measureunit",
                verbose_name="Unidad de Medida",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measure_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.measureunit",
                verbose_name="Unidad de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="category_product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.categoryproduct",
                verbose_name="Categoria de Producto",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categoryproduct",
                verbose_name="Categoria de Producto",
            ),
        ),
    ]
